# Generated by Django 5.2.17 on 2026-09-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='committee/')),
                ('order', models.IntegerField(default=0, help_text='Order in which they appear (e.g. 1, 2, 3)')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
