# Generated by Django 5.2.17 on 2026-09-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='message',
        ),
        migrations.AddField(
            model_name='donation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
